repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0  # Use the latest release
    hooks:
      - id: codespell
        args: ["--skip=*.png,*.jpg,*.jpeg,*.gif,*.txt", "--ignore-words-list=hte"]
        files: \.md$
        fail_fast: true
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-no-eval
