version: '3.8'

services:
  llm_service:
    image: key2life/llm-server:latest
    build: .
    container_name: llm-server
    environment:
      - LLM_MODEL=${LLM_MODEL}
      - CHROMADB_HOST=${CHROMADB_HOST}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
      - BOOTSTRAP_SERVER=${BOOTSTRAP_SERVER}
      - SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY_URL}
      - LLM_TOPIC_REQUEST=${LLM_TOPIC_REQUEST}
      - LLM_TOPIC_RESPONSE=${LLM_TOPIC_RESPONSE}
      - PERMISSIONS_URL=${PERMISSIONS_URL}
    networks:
        - llm-cloud-network
networks:
    llm-cloud-network:
        driver: bridge
